### ISSUE TITLE
Nested scss definition

### ISSUE THREAD

**Issue by FDiskas** [pucelle/vscode-css-navigation#14]
![image](https://user-images.githubusercontent.com/468006/59093270-2f781800-891c-11e9-9a51-38099accf9ba.png)

Not sure is it possible to not suggest definition if the css path is not correct for current markup. I mean if `--justify` is a requirement for parent then it should not be in definition list if current html is not match :/
Probably to much I'm asking here :)

**Comment by pucelle** [comment]
Hi, FDiskas, Thanks for your suggestion. I also found the same problem before the plugin's first release, and I did a short mark at [here](https://github.com/pucelle/vscode-css-navigation#many-duplicate-definotions-got-can-you-limit-the-results-to-only-in-files-specified-by-link-tags-or-check-parent-nodes-to-ensure-the-whole-selector-match).

Yes it's possible and not very hard to check parent nodes and make sure the whole selector match, although there is a small rate to make mistake: e.g., you only have a small piece of code `<div class="x">`, and it may can't match selector `.a .x`...

So I planed when there are several CSS definitions got, e.g., `.a .x`, `.b .x`, `.c .x`, I will check parent elements to filter these results, and if no parent match, I still keep all the results. This is the best solution I found until now. If you have some good ideas, welcome to note here.

Otherwise sorry I'm very busy these days. I will complete all the planned features in some days after
my main work finished, in about 2~3 months.

**Comment by pucelle** [comment]
Reopen, scheduled at early of September.

**Comment by pucelle** [comment]
Postpone to October.

**Comment by pucelle** [comment]
Sorry, I started my new career as a graphic algorithm engineer these days, I will keep working on this plugin after my hard time over.

**Comment by pucelle** [comment]
Closed, don't have a plan to implement it right now.
Otherwise, From my experience, nesting selectors is a bad idea, we should focus on an unique and more meaningful class name.

**Comment by pucelle** [comment]
Reopen as more requests continuous come, Reference to #50.
