### ISSUE TITLE
Supports parsing all CSS codes in `.vue` files and gives completion service

### ISSUE THREAD

**Issue by pucelle** [pucelle/vscode-css-navigation#19]
_Originally posted by @pucelle in https://github.com/pucelle/vscode-css-navigation/issues/18#issuecomment-515954670_

**Comment by msacchetti** [comment]
**After digging deeper i realize:**

About autocomplete in .vue files - opening up the Output console for this extension, i now see that autocomplete does not work at all in vue. It always returns: No completion found, 1 ms cost. _This is not even needed_ at all because the official vue extension for vs code does it already.

About goto/peek in .vue files - goto/peek in vue files works fine (it shouldn't search other .vue files like i had said). It works in vue files because i have "search in <style> tags" turned on.

So everything is actually working fine for me now in regards to autocompletion. I have a vue issue about scss files that i will open another ticket for.

**Comment by pucelle** [comment]
Ok,Thanks.
