### ISSUE TITLE
Class finding

### ISSUE THREAD

**Issue by mmcmm** [pucelle/vscode-css-navigation#3]
I noticed that if you have `tag.someClass {...}` or `.someClass .someAnotherClass {...}` the `go to`, maybe auto completion too, doesn't work anymore.

**Comment by pucelle** [comment]
Yes, this is what I currently intend to do:
Current implementation in finding definition is very simple, it focus on looking for the most import part of the selector, which is the start part of the selector. That means, `.class1.class2` will match `.class1`, but `.class2.class1` not match, and `p.class1` not match too.
...
After consider about it more carefully, I think this should be not correct, `.class2.class1` should match `.class1`, and `p.class1` too. So I will fix this in one or two days.

For the second `.someClass .someAnotherClass`, it will not match `.someClass`, since the  `.someClass .someAnotherClass` was defined for `.someAnotherClass`, and `.someClass` is just his parent.

I hope the extension can just work as what web developers think it. So if you have more ideas or reasons, just list them here. 

Thanks.

**Comment by pucelle** [comment]
I released version 1.2.0 to support selectors like `.class1.class-match`, `p.class-match`.
Here is my test cases:
https://github.com/pucelle/vscode-css-navigation/blob/10a81c81a072af82d9bbbae3edb1a52afae7d378/client/test/fixture/css/test.css#L68-L72

Otherwise, I don't plan to find parent selector as definitions because users should expect the styles declarations defined for the selectors he is looking for.

Supporting completion for parent selectors is possible, but not help much. I would suggest you define some styles for the selector you need completion, and reduce the usage of nesting selectors, which will slow your browser's rendering performance. Otherwise, supports parent selectors completion will increase the CSS parsing time and memory usage, and also increase searching completion time.
