### ISSUE TITLE
[feature request] go to class inside of .vue file

### ISSUE THREAD

**Issue by LifeIsStrange** [pucelle/vscode-css-navigation#30]
Currently from the template of a vue component, I can go to a css class, defined in an external css file.

What I cannot do, is: in the template of  vue component to go to a css class, defined inside another vue component.

**Comment by pucelle** [comment]
Hi, LifeIsStrange, Can you provide an example like some code pieces about it?

I will research it but I cant promise to support it, because what this plugin trying to do is to support standard CSS language. So may be it is better that the function you want should be implemented by a Vue plugin.

**Comment by pucelle** [comment]
Closed because no feedback.

**Comment by LifeIsStrange** [comment]
@pucelle yeah sorry I switched to webstorm in the meantime

**Comment by pucelle** [comment]
Never mind, ^_^

**Comment by WebMechanic** [comment]
I'd like you to "reopen" this, 'cos the extension does a great job everywhere else, but it is not work in the `<template>` and `<style>` elements of [Vue Component files](https://vuejs.org/v2/style-guide/#Component-style-scoping-essential) with their `.vue` file extension.

I added the extension to the list, but it didn't help :)

If you need help on the specifics of these files I'd be happy to help.

**Comment by pucelle** [comment]
Hi, WebMechanic, Can you provide me some code pieces, I'm not a `vue` user.
I believe this should be implemented soon.
Thanks.

**Comment by pucelle** [comment]
I made a test case at https://github.com/pucelle/vscode-css-navigation/blob/master/client/test/fixture/index.vue to cover scoped style.
Please help to check whether it's correct. and it would be nice if you can paste some representative codes.

Don't know whether global style is important enough for a vue developer, It would cost some time to support it.

**Comment by WebMechanic** [comment]
Hey,

I'll see if I can find some real code to create a gist.

"global styles" (not sure that's an official term) are just whatever else there is in the project. It'd be anything "not scoped", so there should be no difference in how you handle that today with any other .html. 
It's all the separate .css, .scss or .less files and what any .html in the project may contain inline.

I call them "global" because style rules from these files can of course be used in the markup of a component, especially if it does NOT provide its own scoped style. It some "app.css" has a `h1` selector it will of course apply to **any** `<h1>` present in **any** .vue file of the project.

> **Note:** I forgot that there is an optional "JSX" plugin for vue that allows you to use that syntax in the script part. I don't use that, so it slipped my mind. There's probably more but that's maybe for a future version :-)

`<style src>` is not used, and IIRC neither are CSS `@import`. Loading external CSS files is dome like loading JS modules in the script block `import from "./assets/stuff.css" and depends on the bundler.
**The concept of "href" or "src" does not apply to `.vue` files.** They are neither parsed nor loaded by the browser, but "containers" for what makes a SFC in Vue. Instead of having three distinct files (.html, .js, .css) the related code is just combined in a single .vue file.
Vue will rip these elements apart and handle them internally and individually when the code is compiled, transpiled and bundled. None of this process is of any concern to your extension: its markup and style rules.

- `<style>` plain css, **unscoped**. Just like any other style element in a regular html. May "leak" outside this component into others when used on the same final page.
- `<style type="scss">`, Sass stylesheet, **unscoped**. Same as unscoped vanilla .css, Becomes part of the global bundle with all the other .scss and .css. At compile time, the contents will be extracted, and bundled with other .scss for sass to process.
- Same with type="less" , just a different processor that get's fed the content of this element.
- `<style scoped>` (vanilaa css) or `<style scoped type="scss">` (Sass): Any rules in here apply only to the markup within the sibling `<template>` element of the .vue file. Other styles or files cannot make use of the stylerules, even if selectors **look** identical.

Vue does not use the markup "verbatum", but compiles it into JS objects for faster processing, then reassembles it back into the DOM _at runtime_ in the browser.

At compile time the selectors of scoped stylessheet and the markup are extended. All selectors from a scoped stylesheet are prefixed with a random `[data-xxxx]` selector and HTML-Elements of that .vue file will receive a matching `data-xxx` attribute.

```html
<!-- Component.vue -->
<template>
 <dl>
   <dt>Username</dt>
    <dd>{{ user.firstname}} {{ user.firstname}}</dd>
   <dt>e-Mail</dt>
    <dd>{{ user.email}}</dd>
 </dl>
</template>
<style scoped>
dl {margin-left:0; font-size:1rem}
dt {font-size:1.2em: color:navy}
dd {text-transform:none}
</style>
```
Elsewhere, maybe in "./assets/base.css"
```css
body {color:black}
dl, dt, dd {font-family:"Fira Sans",Arial,sans-serif}
```

For your extension this should be no different than any .html that has an inline style element and a link to the "asset/base.css".
Just pretend `template` would be the `body` of a very small html file.

Only **at compile time** and eventually **at runtime** in the browser -- long after both your extension and Code have seen the code -- the presence of that scoped stylesheet transforms markup and selectors into sth like this (the template element will be dumped):
```html
<dl data-6923468>
  <dt data-6923468>Username</dt>
     <dd data-6923468>Jane Doe</dd>
  <dt data-6923468>e-Mail</dt
    <dd>jane@example.com</dd>
</dl>
```

In some fat separate .css bundle found is a "dist/" or "built/" folder with **all the other (preprocessed) styles** of that project/page:
```css
/* assets/base.css */
body {color:black}
dl, dt, dd {font-family:"Fira Sans",Arial,sans-serif}

/* components/Component.vue */
dl[data-6923468] {margin-left:0; font-size:1rem}
dt[data-6923468] {font-size:1.2em: color:navy}
dd[data-6923468] {text-transform:none}
```

Hope this clears thing up a little.

**Comment by pucelle** [comment]
Thanks for your detailed comment, I'll work on this soon.

**Comment by WebMechanic** [comment]
no rush, I'm glad you lookinto it.

**Comment by WebMechanic** [comment]
Just found this https://v3.vuejs.org/api/sfc-style.html
Have a nice weekend!

**Comment by WebMechanic** [comment]
any progress on this?

**Comment by pucelle** [comment]
Well, it's really shame to not deal with this reasonable feature in more than one year.
Some recent news is that I will soon work on a project which was programmed with `vue`, so I guess I will work on this feature soon.
Sorry for the being late again.

**Comment by pucelle** [comment]
After some consideration, this plugin will focus on HTML-like syntax, so it will not support Vue particular syntax.
Includes:
1. Finding global CSS declarations defined in another Vue file.
2. Detecting imported CSS files from a <script> tag in a Vue file.
