### ISSUE TITLE
[Feature request] Find references from HTML to HTML

### ISSUE THREAD

**Issue by jportoles** [pucelle/vscode-css-navigation#32]
Sometimes you may want to look up references for a class or a id name while browsing an HTML file. Currently you can highlight a selector in a CSS file and then press Shift+F12 to find other HTML files where it appears. I suggest that it should be possible to highlight an id or a class within a HTML file, and then press Shift+F12 to find instances of it in other HTML files. It's a small thing but since the functionality is already there in CSS files, why not?

**Comment by pucelle** [comment]
Yes, you are right, this feature sounds good, and it's not hard to implement it since I already have a module to collect classes and ids from HTML file.
The only problem is I'm busy these days, I planed more features for this plugin but still don't have time, So I can't promise a date, but I will do it once I have some time.

**Comment by pucelle** [comment]
https://github.com/pucelle/vscode-css-navigation/blob/74a72519baa585a5777248ca5aa0aeb0a4b91010/server/src/server.ts#L135
Check function here and you can dive inside from it.

But the functionality doesn't process things in a linear mode, it works more like a system. You may find it's hard to extend before you know what it works.

Otherwise, You may see there are many English syntax mistakes in my code, Sorry for this because English is not my mother language.

**Comment by pucelle** [comment]
v1.10.1 just released, please try it, thanks.
