### ISSUE TITLE
Single character then dash class name bug

### ISSUE THREAD

**Issue by onetrev** [pucelle/vscode-css-navigation#54]
I use [namespacing](https://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/#the-namespaces) for my classs names, but it causes a glitch. So to explain...

If I have a class name such as: `.c-footer-logo` then go to insert that class in my HTML, it autocompletes with duplicate characters for the first two chars. In other words, the class name comes in as `c-c-footer-logo`. Hopefully that makes sense. It works fine if you have two characters before a dash, so for example `.cc-footer-logo` works fine.

PS, the link to "Issues" on the VS Code Marketplace for this extension 404s, as it points to https://github.com/pucelle/vscode-navigation/issues  Just wanted to let you know. :)

**Comment by pucelle** [comment]
Thanks, Yes this link is wrong. Thanks for pointing it out and I already changed it...

Great catch! This issue exist because I know nothing about the auto-completion range when I made this plugin one year ago. So, auto-completion have no problem if you input and get completion from the first char, but will have duplicate chars otherwise.

I will fix this issue soon. And thanks very much.

**Comment by kanlukasz** [comment]
I just want to confirm that this is also happening in my environment:
![gif4](https://user-images.githubusercontent.com/30685349/112036749-4dd6f400-8b41-11eb-9be5-db9567d5acd8.gif)

**Comment by pucelle** [comment]
Thanks, very clear, I know how to fix this and will fix it soon.

**Comment by pucelle** [comment]
V1.10.6 released just some seconds ago.

**Comment by onetrev** [comment]
This now works perfectly -- thank you!!
